/**
 * Task API Integration Tests
 *
 * Tests for task management endpoints
 * Demonstrates testing approach generated by AI agents
 */

import request from 'supertest';
import { createApp } from '../src/server';
import { Application } from 'express';
import { TaskPriority, TaskStatus } from '../src/models/Task';

describe('Task API', () => {
  let app: Application;
  let authToken: string;
  let testUserId: string;
  let testTaskId: string;

  beforeAll(async () => {
    app = createApp();

    // Register and login a test user
    const registerRes = await request(app)
      .post('/api/v1/auth/register')
      .send({
        email: 'test@example.com',
        password: 'Test123!@#',
        name: 'Test User'
      });

    const loginRes = await request(app)
      .post('/api/v1/auth/login')
      .send({
        email: 'test@example.com',
        password: 'Test123!@#'
      });

    authToken = loginRes.body.data.token;
    testUserId = loginRes.body.data.user.id;
  });

  describe('POST /api/v1/tasks', () => {
    it('should create a new task with valid data', async () => {
      const taskData = {
        title: 'Complete project documentation',
        description: 'Write comprehensive API documentation',
        priority: TaskPriority.HIGH,
        status: TaskStatus.TODO,
        tags: ['documentation', 'important']
      };

      const response = await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send(taskData)
        .expect(201);

      expect(response.body.success).toBe(true);
      expect(response.body.data).toMatchObject({
        title: taskData.title,
        description: taskData.description,
        priority: taskData.priority,
        status: taskData.status,
        userId: testUserId
      });
      expect(response.body.data.id).toBeDefined();
      testTaskId = response.body.data.id;
    });

    it('should fail to create task without authentication', async () => {
      const taskData = {
        title: 'Unauthorized task'
      };

      await request(app)
        .post('/api/v1/tasks')
        .send(taskData)
        .expect(401);
    });

    it('should fail to create task with invalid title', async () => {
      const taskData = {
        title: '', // Empty title
        priority: TaskPriority.LOW
      };

      await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send(taskData)
        .expect(400);
    });
  });

  describe('GET /api/v1/tasks', () => {
    it('should retrieve all tasks for authenticated user', async () => {
      const response = await request(app)
        .get('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(Array.isArray(response.body.data)).toBe(true);
      expect(response.body.pagination).toBeDefined();
    });

    it('should filter tasks by status', async () => {
      const response = await request(app)
        .get('/api/v1/tasks')
        .query({ status: TaskStatus.TODO })
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      response.body.data.forEach((task: any) => {
        expect(task.status).toBe(TaskStatus.TODO);
      });
    });

    it('should support pagination', async () => {
      const response = await request(app)
        .get('/api/v1/tasks')
        .query({ page: 1, limit: 10 })
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.pagination.page).toBe(1);
      expect(response.body.pagination.limit).toBe(10);
    });
  });

  describe('GET /api/v1/tasks/:id', () => {
    it('should retrieve a specific task by ID', async () => {
      const response = await request(app)
        .get(`/api/v1/tasks/${testTaskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.id).toBe(testTaskId);
    });

    it('should return 404 for non-existent task', async () => {
      const fakeId = '00000000-0000-0000-0000-000000000000';
      await request(app)
        .get(`/api/v1/tasks/${fakeId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(404);
    });
  });

  describe('PATCH /api/v1/tasks/:id', () => {
    it('should update task status', async () => {
      const updates = {
        status: TaskStatus.IN_PROGRESS
      };

      const response = await request(app)
        .patch(`/api/v1/tasks/${testTaskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .send(updates)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.data.status).toBe(TaskStatus.IN_PROGRESS);
    });

    it('should update multiple task fields', async () => {
      const updates = {
        title: 'Updated task title',
        priority: TaskPriority.URGENT,
        tags: ['updated', 'urgent']
      };

      const response = await request(app)
        .patch(`/api/v1/tasks/${testTaskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .send(updates)
        .expect(200);

      expect(response.body.data.title).toBe(updates.title);
      expect(response.body.data.priority).toBe(updates.priority);
    });
  });

  describe('DELETE /api/v1/tasks/:id', () => {
    it('should delete a task', async () => {
      const response = await request(app)
        .delete(`/api/v1/tasks/${testTaskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);

      // Verify task is deleted
      await request(app)
        .get(`/api/v1/tasks/${testTaskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(404);
    });
  });

  describe('PATCH /api/v1/tasks/bulk', () => {
    it('should bulk update multiple tasks', async () => {
      // Create multiple tasks first
      const task1 = await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send({ title: 'Task 1' });

      const task2 = await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send({ title: 'Task 2' });

      const taskIds = [task1.body.data.id, task2.body.data.id];
      const updates = { status: TaskStatus.COMPLETED };

      const response = await request(app)
        .patch('/api/v1/tasks/bulk')
        .set('Authorization', `Bearer ${authToken}`)
        .send({ taskIds, updates })
        .expect(200);

      expect(response.body.data.updated).toBe(2);
    });
  });
});
